name: DependencyPipeline

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out pipeline repository
      - name: 'Checkout pipeline repo'
        uses: actions/checkout@v3

      # Updated the dependency details repo
      - name: check the diff for dependencies in package.json
        uses: ./.github/actions/get-dependencies
        with:
          gthub-org-name: ${{ secrets.GTHUB_ORGNAME }}
          gthub-username: ${{ secrets.GTHUB_USERNAME }}
          gthub-token: ${{ secrets.GTHUB_TOKEN }}
          gthub-user: ${{secrets.GTHUB_USER}}
          gthub-user-email: ${{secrets.GTHUB_USER_EMAIL}}
          dependency-repo-name: 'dependency-details'
